apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: prometheus
  name: prometheus
  namespace: kube-system
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    k8s-app: prometheus
  sessionAffinity: None
  type: NodePort
